tabl_lang = {"Afghanistan": "AF",
             "Dominicaine": "DO",
             "Lituanie": "LT",
             "Sahara Occidental": "EH",
             "Afrique du Sud": "ZA",
             "Dominique": "DM",
             "Luxembourg": "LU",
             "Saint-Kitts-et-Nevis": "KN", 
             "Albanie": "AL",
             "Egypte": "EG",
             "Macao": "MO",
             "Saint-Marin": "SM",
             "Algérie": "DZ",
             "Fidji": "FJ",
             "Macédoine": "MK",
             "Saint-Pierre-et-Miquelon": "PM",
             "Andorre": "AD",
             "El Salvador": "SV",
             "Madagascar": "MG",
             "Saint-Siège": "VA",
             "Angola": "AO",
             "Emirats Arabes Unis": "AE",
             "Malaisie": "MY",
             "Saint-Vincent-et-les-Grenadines": "VC",
             "Anguilla": "AI",
             "Equateur": "EC",
             "Malawi": "MW",
             "Sainte-Hélène": "SH",
             "Antarctique": "AQ",
             "Erythrée": "ER",
             "Maldives": "MV",
             "Sainte-Lucie": "LC",
             "Antigua-et-Barbuda": "AG",
             "Espagne": "ES",
             "Mali": "ML",
             "Salomon": "SB",
             "Antilles Néerlandaises": "AN",
             "Estonie": "EE",
             "Malte": "MT",
             "Samoa": "WS",
             "Arabie Saoudite": "SA",
             "Etats-Unis d’Amérique": "US",
             "Iles Mariannes": "MP",
             "Samoa americaine": "AS",
             "Argentine": "AR",
             "Ethiopie": "ET",
             "Maroc": "MA",
             "Săo Tomé et Principe": "ST",
             "Arménie": "AM",
             "Iles Falklands": "FK",
             "Iles Marshall": "MH",
             "Sénégal": "SN",
             "Aruba": "AW",
             "Iles Feroë": "FO",
             "Martinique": "MQ",
             "Seychelles": "SC",
             "Australie": "AU",
             "Fidji": "FJ",
             "Ile Maurice": "MU",
             "Sierra Leone": "SL",
             "Autriche": "AT",
             "Finlande": "FI",
             "Mauritanie": "MR",
             "Singapour": "SG",
             "Azerbaïdjan": "AZ",
             "France": "FR",
             "Mayotte": "YT",
             "Slovaquie": "SK",
             "Bahamas": "BS",
             "Gabon": "GA",
             "Mexique": "MX",
             "Slovénie": "SI",
             "Bahreïn": "BH",
             "Gambie": "GM",
             "Micronésie": "FM",
             "Somalie": "SO",
             "Bangladesh": "BD",
             "Géorgie": "GE",
             "Moldova": "MD",
             "Soudan": "SD",
             "Barbade": "BB",
             "Ghana": "GH",
             "Monaco": "MC",
             "Sri Lanka": "LK",
             "Bélarus": "BY",
             "Gibraltar": "GI",
             "Bélarus": "BY",
             "Gibraltar": "GI",
             "Mongolie": "MN",
             "Suède": "SE",
             "Belgique": "BE",
             "Grèce": "GR",
             "Montserrat": "MS",
             "Suisse": "CH",
             "Belize": "BZ",
             "Grenade": "GD",
             "Mozambique": "MZ",
             "Suriname": "SR",
             "Bénin": "BJ",
             "Groenland": "GL",
             "Myanmar": "MM",
             "Iles Svalbard et Jan Mayen": "SJ",
             "Bermudes": "BM",
             "Guadeloupe": "GP",
             "Namibie": "NA",
             "Swaziland": "SZ",
             "Bhoutan": "BT",
             "Guam": "GU",
             "Nauru": "NR",
             "Syrie": "SY",
             "Bolivie": "BO",
             "Guatemala": "GT",
             "Népal": "NP",
             "Tadjikistan": "TJ",
             "Bosnie-Herzégovine": "BA",
             "Guinée": "GN",
             "Nicaragua": "NI",
             "Taiwan": "TW",
             "Botswana": "BW",
             "Guinée-Bissau": "GW",
             "Niger": "NE",
             "Tanzanie": "TZ",
             "Ile Bouvet": "BV",
             "Guinée Equatoriale": "GQ",
             "Nigéria": "NG",
             "Tchad": "TD",
             "Brésil": "BR",
             "Guyana": "GY",
             "Nioué": "NU",
             "Tchéquie": "CZ",
             "Brunéi": "BN",
             "Guyane Française": "GF",
             "Thaïlande": "TH",
             "Ile Norfolk": "NF",
             "Bulgarie": "BG",
             "Haîti": "HT",
             "Norvège": "NO",
             "Timor oriental": "TP",
             "Burkina Faso": "BF",
             "Honduras": "HN",
             "Nouvelle-Calédonie": "NC",
             "Togo": "TG", 
             "Burundi": "BI",
             "Hongkong": "HK",
             "Nouvelle-Zélande": "NZ",
             "Tokélau": "TK",
             "Iles Caïmanes": "KY",
             "Hongrie": "HU", 
             "Oman": "OM",
             "Tonga": "TO",
             "Cambodge": "KH",
             "Inde": "IN",
             "Ouganda": "UG",
             "Trinité-et-Tobago": "TT",
             "Cameroun": "CM",
             "Indonésie": "ID",
             "Ouzbékistan": "UZ",
             "Tunésie": "TN",
             "Canada": "CA",
             "Iran": "IR",
             "Pakistan": "PK", 
             "Turkménistan": "TM",
             "Cap-Vert": "CV",
             "Iraq": "IQ",
             "Palaos": "PW",
             "Iles Turks et Caïques": "TC",
             "Centrafrique": "CF",
             "Palestine": "PS",
             "Irlande": "IE",
             "Turquie": "TR",
             "Tuvalu": "TV",
             "Panama": "PA",
             "Islande": "IS",
             "Chili": "CL",
             "Papouasie-Nouvelle-Guinée": "PG",
             "Israël": "IL",
             "Chine": "CN",
             "Ukraine": "UA",
             "Uruguay": "UY",
             "Paraguay": "PY",
             "Italie": "IT",
             "Ile Christmas": "CX",
             "Vanuatu": "VU",
             "Pays-Bas": "NL",
             "Jamaïque": "JM",
             "Chypre": "CY",
             "Venezuela": "VE",
             "Pérou": "PE",
             "Japon": "JP",
             "Iles Cocos": "CC",
             "Vierges britanniques": "VG",
             "Philippines": "PH",
             "Jordanie": "JO",
             "Colombie": "CO",
             "Vierges des Etats Unis": "VI",
             "Pitcairn": "PN",
             "Kazakstan": "KZ",
             "Comores": "KM",
             "Congo-Brazaville": "CG",
             "Vietnam": "VN",
             "Peru": "PE",
             "Kenya": "KE",
             "Congo": "CD",
             "Wallis et Futuna": "WF",
             "Pitcaim": "PN",
             "Kirghizistan": "KG",
             "Yémen": "YE",
             "Pologne": "PL",
             "Kiribati": "KI",
             "Iles Cook": "CK",
             "Polynésie Française": "PF",
             "Koweït": "KW",
             "Corée du Nord": "KP",
             "Yougoslavie": "YU",
             "Zambie": "ZM",
             "Porto Rico": "PR",
             "Laos": "LA",
             "Corée du Sud": "KR",
             "Zimbabwe": "ZW",
             "Portugal": "PT",
             "Lesotho": "LS",
             "Costa Rica": "CR",
             "Qatar": "QA",
             "Lettonie": "LV",
             "Côte d’Ivoire": "CI",
             "Réunion": "RE",
             "Liban": "LB",
             "Croatie": "HR",
             "Royaume-Uni": "RO",
             "Libéria": "LR",
             "Cuba": "CU",
             "Russie": "RU",
             "Libye": "LY",
             "Danemark": "DK",
             "Djibouti": "DJ",
             "Liechtenstein": "LI",
             "Rwanda": "RW",
             "Autre pays": "ZZ"

}

list_rg = ["Ain",
	"Aisne",
	"Allier",
	"Alpes-de-Haute-Provence",
	"Hautes-Alpes",
	"Alpes-Maritimes",
	"Ardèche",
	"Ardennes",
	"Ariège",
	"Aube",
	"Aude",
	"Aveyron",
	"Bouches-du-Rhône",
	"Calvados",
	"Cantal",
	"Charente",
	"Charente-Maritime",
	"Cher",
	"Corrèze",
	"Corse-du-Sud",
	"Haute-Corse",
	"Côte-d'Or",
	"Côtes d'Armor",
	"Creuse",
	"Dordogne",
	"Doubs",
	"Drôme",
	"Eure",
	"Eure-et-Loir",
	"Finistère",
	"Gars",
    "Haute-Garonne",
	"Gers",
	"Gironde",
	"Hérault",
	"Ille-et-Vilaine",
	"Indre",
	"Indre-et-Loire",
	"Isère",
	"Jura",
	"Landes",
	"Loir-et-Cher",
	"Loire",
	"Haute-Loire",
	"Loire-Atlantique",
	"Loiret",
	"Lot",
	"Lot-et-Garonne",
	"Lozère",
	"Maine-et-Loire",
	"Manche",
	"Marne",
	"Haute-Marne",
	"Mayenne",
	"Meurthe-et-Moselle",
	"Meuse",
	"Morbihan",
	"Moselle",
	"Nièvre",
	"Nord",
	"Oise",
	"Orne",
	"Pas-de-Calais",
	"Puy-de-Dôme",
	"Pyrénées-Atlantiques",
	"Hautes-Pyrénées",
	"Pyrénées-Orientales",
	"Bas-Rhin",
	"Haut-Rhin",
	"Rhône",
	"Haute-Saône",
	"Saône-et-Loire",
	"Sarthe",
	"Savoie",
	"Haute-Savoie",
	"Paris",
	"Seine-Maritime",
	"Seine-et-Marne",
	"Yvelines",
	"Deux-Sèvres",
	"Somme",
	"Tarn",
	"Tarn-et-Garonne",
	"Var",
	"Vaucluse",
	"Vandée",
	"Vienne",
	"Haute-Vienne",
	"Vosges",
	"Yonne",
	"Territoire de Belfort",
	"Essonne",
	"Hauts-de-Seine",
	"Seine-St-Denis",
	"Val-de-Marne",
	"Val-D'Oise",
	"Guadeloupe",
	"Martinique",
	"Guyane",
	"La Réunion",
	"Mayotte"
    ]

list_us_states = ["Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "Californie",
    "Caroline du Nord",
    "Caroline du Sud",
    "Colorado",
    "Connecticut",
    "Dakota du Nord",
    "Dakota du Sud",
    "Delaware",
    "Floride",
    "Géorgie",
    "Hawaï",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiane",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "État de New York",
    "Nouveau-Mexique",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvanie",
    "Rhode Island",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginie",
    "Virginie-Occidentale",
    "Washington",
    "Wisconsin",
    "Wyoming"
    ]